steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME', '.' ]
# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=asia.gcr.io/$PROJECT_ID/$TAG_NAME
#   - --cache=true
#   - --cache-ttl=6h  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', '$TAG_NAME','--max-instances', '3', '--memory', '256Mi', '--image', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated', '--vpc-connector', 'javahu20', '--add-cloudsql-instances', 'hu-java-test1', '--set-env-vars', 'DBN=$TAG_NAME']
logsBucket: 'gs://hu18-groupb-java_cloudbuild'

