spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/elearningdb"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:123}"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
