spring:
  datasource:
    url: "jdbc:postgresql://10.111.192.3:5432/${DBN}"
    username: "${DBN}"
    password: "${DBN}"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "false"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: "hu18-groupb-java:asia-southeast1:hu-java-test1"
        database-name: "${DBN}"
